local ui = require('../../lua/ui')
local same = require('../../lua/ui.lua')
assert(ui == same)
local now = 1000
time.millis = function() return now end
assert(ui.elapsed(0x7ffffffe, 1) == 3)
display.clear(0)
ui.center(0, 'AB', 0xffffff)
local centered = display.frame()
display.clear(0)
display.text(4, 0, 'AB', 0xffffff)
assert(display.frame() == centered)
display.clear(0)
ui.scroll(10, 'SCROLLING', now - 845, 0xabcdef)
local scrolling = display.frame()
display.clear(0)
display.text(-2, 10, '   SC', 0xabcdef)
assert(display.frame() == scrolling)
display.clear(0)
ui.bar(7, 50, 100, 0x123456, 16)
assert(display.get(7, 7) == 0x123456 and display.get(8, 7) == 0)
ui.bar(8, 500, 100, 0x654321, 100)
assert(display.get(15, 8) == 0x654321)
ui.bar(9, -1, 100); ui.bar(9, 1, 0)
assert(display.get(0, 9) == 0)
ui.indicator(true)
assert(display.get(15, 6) == 0x20ff40)
ui.indicator(false)
assert(display.get(15, 6) == 0x503010)
local view = ui.screen()
view.set('TEST', 'WAIT')
view.draw(false, 1, 5)
local first = display.frame()
view.set('NEXT', 'DONE')
view.draw(true)
assert(display.frame() == first)
now = now + 100
view.draw(true)
assert(display.frame() ~= first and display.get(15, 6) == 0x20ff40)
local other = ui.screen()
other.set('AB', 'CD'); other.draw()
local second = display.frame()
now = now + 100
view.draw(true)
assert(display.frame() ~= second)
return 'UI helpers passed'
