#!/usr/bin/env python3
"""Generate the fixed HOGP database, preserving every stock control handle."""
import argparse
import hashlib
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser(description=__doc__)
p.add_argument('--check', action='store_true')
a = p.parse_args()
stock = (ROOT/'firmware/306007.MVA').read_bytes()
assert hashlib.sha256(stock).hexdigest() == 'fc16341c005b11d0ac476917dc2fd98c9bc7481b92a183e64bfe209801566544'
db = bytearray(stock[0x60f+0x15b644:0x60f+0x15b77c])
assert len(db) == 312 and db[0] == 1
# Explicit bit usages avoid classifying the remote as an alphabetic keyboard,
# mouse, joystick or stylus. GATT Report Reference carries each report ID.
report = bytes.fromhex('''
05 01 09 06 a1 01 85 01 05 07
09 28 09 29 09 2c 09 4f 09 50 09 51 09 52
15 00 25 01 75 01 95 07 81 02 95 01 81 03 c0
05 0c 09 01 a1 01 85 02
09 cd 09 e2 09 e9 09 ea 09 b5 09 b6 09 b7 09 30
15 00 25 01 75 01 95 08 81 02 c0
''')

def attr(handle, uuid, value=b'', flags=2):
    db.extend(struct.pack('<HHHH', 8+len(value), flags, handle, uuid)+value)

def service(handle, uuid):
    attr(handle, 0x2800, struct.pack('<H', uuid))

def char(handle, uuid, props, value=b'', flags=None):
    attr(handle, 0x2803, struct.pack('<BHH', props, handle+1, uuid))
    attr(handle+1, uuid, value, props if flags is None else flags)

service(0x20, 0x1812)
char(0x21, 0x2a4a, 2, flags=0x102) # dynamic HID Information, including remote wake
char(0x23, 0x2a4b, 2, flags=0x102) # dynamic report map supplied by Lua or default
char(0x25, 0x2a4c, 4, flags=0x105) # dynamic Control Point
for handle, report_id in [(0x27, 1), (0x2b, 2)]:
    # Encrypted reads (bit10); encrypted CCCD writes (bit0).
    char(handle, 0x2a4d, 0x12, flags=0x512)
    attr(handle+2, 0x2902, bytes(2), flags=0x50b)
    attr(handle+3, 0x2908, bytes([report_id, 1]))
service(0x30, 0x180f)
char(0x31, 0x2a19, 2, flags=0x102)
service(0x34, 0x180a)
char(0x35, 0x2a29, 2, b'Divoom')
char(0x37, 0x2a24, 2, b'Ditoo BLE Remote')
char(0x39, 0x2a50, 2, bytes.fromhex('02 88 88 1e 17 01 00'))
# Fixed database across modes and boots: no silent handle reassignment.
service(0x3c, 0x1801)
db.extend(bytes(2))
lines = ['/* Generated by scripts/build-hogp-database.py; do not edit. */',
         'static const unsigned char hogp_default_map[] = {' + ','.join(f'0x{x:02x}' for x in report) + '};',
         'static const unsigned char hogp_database[] = {']
for i in range(0, len(db), 16):
    lines.append('    '+','.join(f'0x{x:02x}' for x in db[i:i+16])+',')
lines += ['};', '']
text = '\n'.join(lines)
out = ROOT/'native/lua-app/bluetooth-hogp-db.h'
if a.check:
    assert out.read_text() == text, 'HOGP database is stale'
else:
    out.write_text(text)
print(f'HOGP database: {len(db)} bytes; report map: {len(report)} bytes')
