#!/usr/bin/env python3
"""Index self-contained 16x16 stock frames without copying their pixels into Lua firmware."""
import argparse
import base64
import binascii
import hashlib
import html
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).resolve().parents[1]
STOCK_SHA = 'fc16341c005b11d0ac476917dc2fd98c9bc7481b92a183e64bfe209801566544'
CODE_OFFSET = 0x60f
ROM_BASE = 0x150000


def stock_code():
    data = (ROOT/'firmware/306007.MVA').read_bytes()
    if hashlib.sha256(data).hexdigest() != STOCK_SHA:
        raise ValueError('stock firmware hash mismatch')
    return data[CODE_OFFSET:-4]


def decode(data):
    if len(data) < 7 or data[0] != 0xaa or data[5] != 0:
        raise ValueError('not an independent palette frame')
    size, delay = struct.unpack_from('<HH', data, 1)
    colors = data[6] or 256
    bits = (colors-1).bit_length()
    if size != 7+3*colors+32*bits or size > len(data):
        raise ValueError('invalid frame size')
    packed = int.from_bytes(data[7+3*colors:size], 'little')
    indices = [(packed >> (i*bits)) & ((1 << bits)-1) for i in range(256)]
    if max(indices) >= colors:
        raise ValueError('invalid palette index')
    pixels = bytes(c for index in indices for c in data[7+index*3:10+index*3])
    return dict(size=size, delay_ms=delay, colors=colors, pixels=pixels)


def frames(code):
    result = []
    for address in range(ROM_BASE, len(code)-7):
        if code[address] != 0xaa:
            continue
        try:
            frame = decode(code[address:address+1031])
        except ValueError:
            continue
        result.append(dict(id=len(result)+1, address=address, **frame))
    return result


def png(pixels):
    def chunk(kind, data):
        return struct.pack('>I', len(data))+kind+data+struct.pack('>I', binascii.crc32(kind+data))
    rows = b''.join(b'\0'+pixels[y*48:(y+1)*48] for y in range(16))
    return (b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR', struct.pack('>IIBBBBB', 16, 16, 8, 2, 0, 0, 0))
            +chunk(b'IDAT', zlib.compress(rows, 9))+chunk(b'IEND', b''))


def outputs(code):
    entries = frames(code)
    # Stable IDs are pinned to this exact stock image, including duplicate frames.
    header = ['/* Generated by scripts/stock-assets.py from pinned stock 306007. */',
              'static const uint32_t asset_images[] = {']
    for start in range(0, len(entries), 8):
        header.append('    '+','.join(f'0x{f["address"]-ROM_BASE:x}' for f in entries[start:start+8])+',')
    header += ['};', '']
    gallery = ['<!doctype html><html lang="en"><meta charset="utf-8">',
               '<meta name="viewport" content="width=device-width,initial-scale=1">',
               '<title>Ditoo stock images</title>',
               '<style>body{background:#202124;color:#eee;font:16px system-ui;margin:24px}'
               'main{display:grid;grid-template-columns:repeat(auto-fill,minmax(130px,1fr));gap:12px}'
               'figure{margin:0;padding:12px;background:#303134;border-radius:6px}'
               'img{width:96px;height:96px;image-rendering:pixelated}'
               'small{display:block;color:#bbb}input{font:inherit;padding:6px;margin:12px 0}</style>',
               '<h1>Ditoo stock images</h1>',
               f'<p>{len(entries)} independently decodable 16×16 frames from stock 306007. '
               'IDs work with <code>assets.image(id)</code> and <code>display.image(x,y,id)</code>. '
               'Duplicates and individual animation frames are retained. This is not a complete '
               'inventory of every native graphic or uploaded file.</p>',
               '<label>Find image ID <input type="search" id="filter" placeholder="e.g. 1"></label><main>']
    for f in entries:
        uri = base64.b64encode(png(f['pixels'])).decode()
        label = html.escape(f'Image {f["id"]}')
        gallery.append(f'<figure id="image-{f["id"]}" data-id="{f["id"]}"><img alt="{label}" '
                       f'src="data:image/png;base64,{uri}"><figcaption>{label}'
                       f'<small>{f["colors"]} colors · {f["delay_ms"]} ms</small>'
                       f'<small>stock 0x{f["address"]:x}</small></figcaption></figure>')
    gallery += ['</main><script>document.getElementById("filter").oninput=function(){'
                'const q=this.value.trim();document.querySelectorAll("figure").forEach(f=>'
                'f.hidden=!!q&&!f.dataset.id.includes(q))}</script></html>', '']
    return {'native/lua-app/assets-index.h':'\n'.join(header),
            'docs/stock-assets.html':'\n'.join(gallery)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check generated files without writing')
    parser.add_argument('--index-only', action='store_true', help='Check or generate only the firmware index')
    args = parser.parse_args()
    generated = outputs(stock_code())
    different = []
    for name, content in generated.items():
        if args.index_only and not name.endswith('.h'):
            continue
        path = ROOT/name
        if not path.exists() or path.read_text() != content:
            different.append(name)
            if not args.check:
                path.write_text(content)
    print(('out of date: ' if args.check else 'updated: ')+', '.join(different) if different else 'stock asset index and gallery match')
    return int(args.check and bool(different))


if __name__ == '__main__':
    raise SystemExit(main())
